import CryptoKit
import XCTest
@testable import Zentty

/// Cross-language interop pin against `companion/wire/vectors/crypto/session-crypto.json`,
/// generated by the TypeScript `@zentty/wire` crypto core (instructed to mirror
/// `CompanionSessionCrypto.swift`). This test reconstructs the fixed test-only
/// keypairs with CryptoKit and runs `CompanionHandshake`/`CompanionSessionCrypto`
/// against the vector: byte-identical directional keys, valid handshake signatures
/// both ways, and a sealed sample that both decrypts and re-seals byte-identically
/// at the same counter.
///
/// If this test fails, do NOT adjust the Swift implementation to match — the TS side
/// was told to mirror Swift, so a mismatch means the vector (or the TS core that
/// produced it) is wrong. Report the exact divergence instead.
///
/// Known, deliberate exception: handshake *signature bytes* are asserted valid
/// (verify under CryptoKit), not byte-equal to the vector's `handshakeSigMac` /
/// `handshakeSigPhone`. CryptoKit's Ed25519 signing derives its per-signature
/// nonce deterministically from the message (RFC 8032), so it reproduces its own
/// output exactly every time — but it does not reproduce the TS core's signature
/// bytes for the same key/message, even though both signatures independently
/// verify against the same transcript and public key. That was confirmed here:
/// `CompanionHandshake.establish(peerSignature:)` accepted the vector's signatures
/// without throwing `invalidHandshakeSignature`, so the transcript and keys line
/// up; only the raw signature bytes differ. This means the TS core's Ed25519
/// signing is not deterministic the same way CryptoKit's is (a different, likely
/// still-valid nonce derivation) — worth a look on the TS side, but not a Swift
/// bug and not something this test should encode as a byte-equality pin.
final class CompanionCryptoVectorTests: XCTestCase {

    private struct Vector: Decodable {
        struct Keys: Decodable {
            let macIdentityPriv: String
            let phoneIdentityPriv: String
            let macEphPriv: String
            let phoneEphPriv: String
        }
        struct DerivedPublicKeys: Decodable {
            let macIdentityPub: String
            let phoneIdentityPub: String
            let macEphPub: String
            let phoneEphPub: String
        }
        struct SealedSample: Decodable {
            let direction: String
            let plaintext: String
            let counter: UInt64
            let ciphertext: String
        }
        struct Expected: Decodable {
            let sendKeyMacToPhone: String
            let sendKeyPhoneToMac: String
            let handshakeSigMac: String
            let handshakeSigPhone: String
            let sealedSample: SealedSample
        }

        let label: String
        let keys: Keys
        let derivedPublicKeys: DerivedPublicKeys
        let expected: Expected
    }

    // MARK: - Loading

    private func vectorURL() throws -> URL {
        let bundle = Bundle(for: type(of: self))
        if let url = bundle.url(
            forResource: "session-crypto",
            withExtension: "json",
            subdirectory: "vectors/crypto"
        ) {
            return url
        }
        // Fallback: some copy phases flatten the folder into the bundle root.
        if let url = bundle.url(forResource: "session-crypto", withExtension: "json") {
            return url
        }
        throw XCTSkip("companion/wire/vectors/crypto/session-crypto.json not found in test bundle")
    }

    private func loadVector() throws -> Vector {
        let url = try vectorURL()
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Vector.self, from: data)
    }

    private func decode(_ base64url: String, label: String) throws -> Data {
        guard let data = CompanionBase64URL.decode(base64url) else {
            XCTFail("failed to base64url-decode \(label)")
            throw XCTSkip("malformed vector field \(label)")
        }
        return data
    }

    // MARK: - Test

    func testSessionCryptoVectorInterop() throws {
        let vector = try loadVector()
        XCTAssertEqual(vector.label, CompanionHandshake.handshakeLabel)

        // MARK: Reconstruct identities and ephemerals from the raw private keys.

        let macIdentity = try Curve25519.Signing.PrivateKey(
            rawRepresentation: try decode(vector.keys.macIdentityPriv, label: "macIdentityPriv")
        )
        let phoneIdentity = try Curve25519.Signing.PrivateKey(
            rawRepresentation: try decode(vector.keys.phoneIdentityPriv, label: "phoneIdentityPriv")
        )
        let macEphemeral = try Curve25519.KeyAgreement.PrivateKey(
            rawRepresentation: try decode(vector.keys.macEphPriv, label: "macEphPriv")
        )
        let phoneEphemeral = try Curve25519.KeyAgreement.PrivateKey(
            rawRepresentation: try decode(vector.keys.phoneEphPriv, label: "phoneEphPriv")
        )

        // Sanity: the vector's own derived public keys match what CryptoKit derives
        // from the private keys, before we even touch CompanionHandshake.
        XCTAssertEqual(
            CompanionBase64URL.encode(macIdentity.publicKey.rawRepresentation),
            vector.derivedPublicKeys.macIdentityPub,
            "vector's macIdentityPub does not match CryptoKit-derived public key for macIdentityPriv"
        )
        XCTAssertEqual(
            CompanionBase64URL.encode(phoneIdentity.publicKey.rawRepresentation),
            vector.derivedPublicKeys.phoneIdentityPub,
            "vector's phoneIdentityPub does not match CryptoKit-derived public key for phoneIdentityPriv"
        )
        XCTAssertEqual(
            CompanionBase64URL.encode(macEphemeral.publicKey.rawRepresentation),
            vector.derivedPublicKeys.macEphPub,
            "vector's macEphPub does not match CryptoKit-derived public key for macEphPriv"
        )
        XCTAssertEqual(
            CompanionBase64URL.encode(phoneEphemeral.publicKey.rawRepresentation),
            vector.derivedPublicKeys.phoneEphPub,
            "vector's phoneEphPub does not match CryptoKit-derived public key for phoneEphPriv"
        )

        // MARK: Handshake signatures, both directions.

        let macSignature = try CompanionHandshake.localSignature(
            role: .mac,
            localIdentity: macIdentity,
            localEphemeralPublicKey: macEphemeral.publicKey.rawRepresentation,
            peerIdentityPublicKey: phoneIdentity.publicKey.rawRepresentation,
            peerEphemeralPublicKey: phoneEphemeral.publicKey.rawRepresentation
        )
        let phoneSignature = try CompanionHandshake.localSignature(
            role: .phone,
            localIdentity: phoneIdentity,
            localEphemeralPublicKey: phoneEphemeral.publicKey.rawRepresentation,
            peerIdentityPublicKey: macIdentity.publicKey.rawRepresentation,
            peerEphemeralPublicKey: macEphemeral.publicKey.rawRepresentation
        )

        // Ed25519 signing is not required to be byte-reproducible across independent
        // implementations that may derive the per-signature nonce differently (only
        // deterministic *within* a single conformant implementation) — so this pins
        // *validity*, not exact bytes, matching the wire contract ("each side signs
        // ... the peer verifies"). `transcript(...)` is private to CompanionHandshake,
        // so reuse `establish(peerSignature:)` itself (which builds the identical
        // transcript internally and throws `invalidHandshakeSignature` on a bad
        // signature) as the verification oracle, in both roles, for both freshly
        // computed and vector-supplied signatures.
        XCTAssertNoThrow(
            try CompanionHandshake.establish(
                role: .phone,
                localIdentity: phoneIdentity,
                localEphemeral: phoneEphemeral,
                peerIdentityPublicKey: macIdentity.publicKey,
                peerEphemeralPublicKey: macEphemeral.publicKey,
                peerSignature: macSignature
            ),
            "locally computed mac signature does not verify"
        )
        XCTAssertNoThrow(
            try CompanionHandshake.establish(
                role: .mac,
                localIdentity: macIdentity,
                localEphemeral: macEphemeral,
                peerIdentityPublicKey: phoneIdentity.publicKey,
                peerEphemeralPublicKey: phoneEphemeral.publicKey,
                peerSignature: phoneSignature
            ),
            "locally computed phone signature does not verify"
        )

        // The vector's own signatures (produced by the TS core) must also verify —
        // exercised for real below via `CompanionHandshake.establish(peerSignature:)`,
        // which throws `invalidHandshakeSignature` on failure.
        let vectorMacSignature = try decode(vector.expected.handshakeSigMac, label: "handshakeSigMac")
        let vectorPhoneSignature = try decode(vector.expected.handshakeSigPhone, label: "handshakeSigPhone")

        // MARK: Establish both sides via CompanionHandshake.establish and compare directional keys.

        let macSession = try CompanionHandshake.establish(
            role: .mac,
            localIdentity: macIdentity,
            localEphemeral: macEphemeral,
            peerIdentityPublicKey: phoneIdentity.publicKey,
            peerEphemeralPublicKey: phoneEphemeral.publicKey,
            peerSignature: vectorPhoneSignature
        )
        let phoneSession = try CompanionHandshake.establish(
            role: .phone,
            localIdentity: phoneIdentity,
            localEphemeral: phoneEphemeral,
            peerIdentityPublicKey: macIdentity.publicKey,
            peerEphemeralPublicKey: macEphemeral.publicKey,
            peerSignature: vectorMacSignature
        )

        let expectedMacToPhoneKey = try decode(vector.expected.sendKeyMacToPhone, label: "sendKeyMacToPhone")
        let expectedPhoneToMacKey = try decode(vector.expected.sendKeyPhoneToMac, label: "sendKeyPhoneToMac")

        // mac's send key == mac->phone key; phone's receive key == mac->phone key too.
        XCTAssertEqual(
            try symmetricKeyData(of: macSession, keyPath: .send),
            expectedMacToPhoneKey,
            "mac session's send key (mac->phone) does not match vector"
        )
        XCTAssertEqual(
            try symmetricKeyData(of: macSession, keyPath: .receive),
            expectedPhoneToMacKey,
            "mac session's receive key (phone->mac) does not match vector"
        )
        XCTAssertEqual(
            try symmetricKeyData(of: phoneSession, keyPath: .send),
            expectedPhoneToMacKey,
            "phone session's send key (phone->mac) does not match vector"
        )
        XCTAssertEqual(
            try symmetricKeyData(of: phoneSession, keyPath: .receive),
            expectedMacToPhoneKey,
            "phone session's receive key (mac->phone) does not match vector"
        )

        // MARK: Sealed sample — open on the phone side (receiver of mac->phone).

        XCTAssertEqual(vector.expected.sealedSample.direction, "mac->phone")
        let sealedFrame = try decode(vector.expected.sealedSample.ciphertext, label: "sealedSample.ciphertext")
        let expectedPlaintext = Data(vector.expected.sealedSample.plaintext.utf8)
        let expectedCounter = vector.expected.sealedSample.counter

        let openedPlaintext = try phoneSession.open(sealedFrame)
        XCTAssertEqual(
            openedPlaintext,
            expectedPlaintext,
            "opening the vector's sealed sample on the phone side did not yield the expected plaintext"
        )

        // MARK: Re-seal at the same counter on the mac side and compare byte-for-byte.

        // `seal` only exposes a monotonic counter starting at 0; advance a *fresh*
        // mac-role session up to `expectedCounter` with throwaway frames, then seal
        // the real plaintext so it lands on the vector's counter.
        let reseal = try CompanionHandshake.establish(
            role: .mac,
            localIdentity: macIdentity,
            localEphemeral: macEphemeral,
            peerIdentityPublicKey: phoneIdentity.publicKey,
            peerEphemeralPublicKey: phoneEphemeral.publicKey,
            peerSignature: vectorPhoneSignature
        )
        XCTAssertGreaterThan(expectedCounter, 0, "test assumes a nonzero counter to exercise counter advancement")
        for _ in 0..<expectedCounter {
            _ = try reseal.seal(Data())
        }
        let resealedFrame = try reseal.seal(expectedPlaintext)

        XCTAssertEqual(
            resealedFrame,
            sealedFrame,
            "re-sealing the vector's plaintext at the vector's counter did not reproduce the vector's sealed bytes"
        )
    }

    // MARK: - Reflection helper

    /// `CompanionSessionCrypto` keeps its `SymmetricKey`s private; reach in via
    /// `Mirror` rather than widening the type's access for a test-only need.
    private enum KeyPath { case send, receive }

    private func symmetricKeyData(of session: CompanionSessionCrypto, keyPath: KeyPath) throws -> Data {
        let mirror = Mirror(reflecting: session)
        let label = keyPath == .send ? "sendKey" : "receiveKey"
        guard
            let child = mirror.children.first(where: { $0.label == label }),
            let key = child.value as? SymmetricKey
        else {
            XCTFail("could not reflect \(label) off CompanionSessionCrypto")
            throw XCTSkip("reflection failed")
        }
        return key.withUnsafeBytes { Data($0) }
    }
}
