import CryptoKit
import XCTest
@testable import Zentty

/// Cross-language interop pin against `companion/wire/vectors/crypto/push-seal.json`,
/// the PHONE-side push-seal vector generated by the TypeScript companion crypto
/// core (see `companion/mobile/scripts/pushSealVectorBuilder.ts`). Loading the
/// phone-generated file here and reproducing it with CryptoKit makes the two
/// implementations cross-check through one checked-in artifact: if the Mac's
/// `CompanionPushSeal` and the mobile `derivePushKey`/`unsealPush` ever disagree
/// on the HKDF salt, ECDH direction, or AEAD layout, this test fails.
///
/// If this test fails, do NOT adjust `CompanionPushSeal` to match — it is the
/// PyNaCl-pinned reference. A mismatch means the vector (or the TS core that
/// produced it) drifted; report the exact divergence instead.
final class CompanionPushSealVectorTests: XCTestCase {

    private struct Vector: Decodable {
        struct Keys: Decodable {
            let macIdentityPriv: String
            let phoneIdentityPriv: String
        }
        struct DerivedPublicKeys: Decodable {
            let macIdentityPub: String
            let phoneIdentityPub: String
        }
        struct SealedSample: Decodable {
            let plaintext: String
            let nonce: String
            let sealed: String
        }
        struct Expected: Decodable {
            let pushKey: String
            let sealedSample: SealedSample
        }

        let label: String
        let keys: Keys
        let derivedPublicKeys: DerivedPublicKeys
        let expected: Expected
    }

    // MARK: - Loading

    private func vectorURL() throws -> URL {
        let bundle = Bundle(for: type(of: self))
        if let url = bundle.url(
            forResource: "push-seal",
            withExtension: "json",
            subdirectory: "vectors/crypto"
        ) {
            return url
        }
        // Fallback: some copy phases flatten the folder into the bundle root.
        if let url = bundle.url(forResource: "push-seal", withExtension: "json") {
            return url
        }
        throw XCTSkip("companion/wire/vectors/crypto/push-seal.json not found in test bundle")
    }

    private func loadVector() throws -> Vector {
        let data = try Data(contentsOf: try vectorURL())
        return try JSONDecoder().decode(Vector.self, from: data)
    }

    private func decode(_ base64url: String, label: String) throws -> Data {
        guard let data = CompanionBase64URL.decode(base64url) else {
            XCTFail("failed to base64url-decode \(label)")
            throw XCTSkip("malformed vector field \(label)")
        }
        return data
    }

    // MARK: - Test

    func testPushSealVectorInterop() throws {
        let vector = try loadVector()
        // The vector's `label` is the HKDF `info` string ("zentty-push").
        XCTAssertEqual(vector.label, String(decoding: CompanionPushSeal.hkdfInfo, as: UTF8.self))

        // Reconstruct both identities from their raw Ed25519 seeds.
        let macIdentity = try Curve25519.Signing.PrivateKey(
            rawRepresentation: try decode(vector.keys.macIdentityPriv, label: "macIdentityPriv")
        )
        let phoneIdentity = try Curve25519.Signing.PrivateKey(
            rawRepresentation: try decode(vector.keys.phoneIdentityPriv, label: "phoneIdentityPriv")
        )

        // Sanity: the vector's derived public keys match what CryptoKit derives.
        XCTAssertEqual(
            CompanionBase64URL.encode(macIdentity.publicKey.rawRepresentation),
            vector.derivedPublicKeys.macIdentityPub,
            "vector's macIdentityPub does not match CryptoKit-derived public key"
        )
        XCTAssertEqual(
            CompanionBase64URL.encode(phoneIdentity.publicKey.rawRepresentation),
            vector.derivedPublicKeys.phoneIdentityPub,
            "vector's phoneIdentityPub does not match CryptoKit-derived public key"
        )

        // Mac seals to phone: sealKey(macPriv, phonePub) must equal the phone-side
        // pushKey the vector expects.
        let macSideKey = try CompanionPushSeal.sealKey(
            macIdentity: macIdentity,
            phoneIdentityPublicKey: phoneIdentity.publicKey.rawRepresentation
        )
        XCTAssertEqual(
            CompanionBase64URL.encode(macSideKey.withUnsafeBytes { Data($0) }),
            vector.expected.pushKey,
            "CryptoKit-derived seal key does not match the vector's pushKey — HKDF salt/info or ECDH drift"
        )

        // ECDH symmetry: the phone derives the identical key from its own private
        // key and the Mac's public key (this is what the NSE computes).
        let phoneSideKey = try CompanionPushSeal.sealKey(
            macIdentity: phoneIdentity,
            phoneIdentityPublicKey: macIdentity.publicKey.rawRepresentation
        )
        XCTAssertEqual(
            phoneSideKey.withUnsafeBytes { Data($0) },
            macSideKey.withUnsafeBytes { Data($0) },
            "push seal key is not symmetric across the ECDH pair"
        )

        // Open the phone-generated sealed sample with the CryptoKit-derived key and
        // confirm it yields the vector's stated plaintext.
        let sealed = try decode(vector.expected.sealedSample.sealed, label: "sealedSample.sealed")
        let opened = try CompanionPushSeal.open(sealed, key: macSideKey)
        XCTAssertEqual(
            String(decoding: opened, as: UTF8.self),
            vector.expected.sealedSample.plaintext,
            "opening the vector's sealed sample did not yield the expected plaintext"
        )
    }
}
