import Foundation

// MARK: - Ed25519 → Curve25519 public-key birational map
//
// libsodium's `crypto_sign_ed25519_pk_to_curve25519` maps an Ed25519 public key
// (an Edwards-curve point, stored as its little-endian y-coordinate with the sign
// bit in the top bit of the last byte) to the corresponding X25519 public key (the
// Montgomery u-coordinate) via the standard birational equivalence:
//
//     u = (1 + y) / (1 - y)   (mod p),   p = 2^255 - 19
//
// The Mac needs this to seal a push payload to a paired phone using only the
// phone's stored Ed25519 identity key (see `CompanionPushSeal`). CryptoKit exposes
// X25519 agreement and Ed25519 signing, but not the conversion between them, so we
// implement the field arithmetic here. Correctness is pinned to libsodium in
// `CompanionPushTests` with vectors generated by PyNaCl.
//
// The field is implemented over eight little-endian `UInt32` limbs (256 bits).
// `UInt32 × UInt32` fits in `UInt64`, so every carry is exact and easy to reason
// about; performance is irrelevant (one conversion per push wake).
enum Curve25519MontgomeryMap {
    /// Number of 32-bit limbs in a field element (256 bits).
    private static let limbCount = 8

    /// p = 2^255 - 19, little-endian 32-bit limbs.
    private static let modulus: [UInt32] = [
        0xFFFF_FFED, 0xFFFF_FFFF, 0xFFFF_FFFF, 0xFFFF_FFFF,
        0xFFFF_FFFF, 0xFFFF_FFFF, 0xFFFF_FFFF, 0x7FFF_FFFF,
    ]

    /// Converts a 32-byte Ed25519 public key to its 32-byte little-endian X25519
    /// (Montgomery u-coordinate) public key. Returns `nil` for a wrong-length input
    /// or the degenerate `y == 1` point (`1 - y == 0`, no inverse).
    static func montgomeryPublicKey(fromEd25519PublicKey edPublicKey: Data) -> Data? {
        guard edPublicKey.count == 32 else { return nil }

        // y = the point's y-coordinate: the key bytes with the sign bit cleared.
        var yBytes = [UInt8](edPublicKey)
        yBytes[31] &= 0x7F
        let y = fromBytes(yBytes)

        let one = fromBytes([1] + [UInt8](repeating: 0, count: 31))
        let oneMinusY = subMod(one, y)
        guard !isZero(oneMinusY) else { return nil }

        let onePlusY = addMod(one, y)
        let u = mulMod(onePlusY, inverse(oneMinusY))
        return Data(toBytes(u))
    }

    // MARK: - Field element conversion

    private static func fromBytes(_ bytes: [UInt8]) -> [UInt32] {
        var limbs = [UInt32](repeating: 0, count: limbCount)
        for i in 0..<limbCount {
            let b0 = UInt32(bytes[i * 4])
            let b1 = UInt32(bytes[i * 4 + 1]) << 8
            let b2 = UInt32(bytes[i * 4 + 2]) << 16
            let b3 = UInt32(bytes[i * 4 + 3]) << 24
            limbs[i] = b0 | b1 | b2 | b3
        }
        return canonical(limbs)
    }

    private static func toBytes(_ limbs: [UInt32]) -> [UInt8] {
        let reduced = canonical(limbs)
        var bytes = [UInt8](repeating: 0, count: 32)
        for i in 0..<limbCount {
            bytes[i * 4] = UInt8(reduced[i] & 0xFF)
            bytes[i * 4 + 1] = UInt8((reduced[i] >> 8) & 0xFF)
            bytes[i * 4 + 2] = UInt8((reduced[i] >> 16) & 0xFF)
            bytes[i * 4 + 3] = UInt8((reduced[i] >> 24) & 0xFF)
        }
        return bytes
    }

    // MARK: - Field arithmetic (mod p)

    private static func addMod(_ a: [UInt32], _ b: [UInt32]) -> [UInt32] {
        var out = [UInt32](repeating: 0, count: limbCount)
        var carry: UInt64 = 0
        for i in 0..<limbCount {
            let sum = UInt64(a[i]) + UInt64(b[i]) + carry
            out[i] = UInt32(sum & 0xFFFF_FFFF)
            carry = sum >> 32
        }
        // Fold the 2^256 carry: 2^256 ≡ 38 (mod p).
        return foldReduce(out, high: [UInt32(carry)])
    }

    private static func subMod(_ a: [UInt32], _ b: [UInt32]) -> [UInt32] {
        // a - b mod p == a + (p - b) mod p; p - b never borrows since b < p.
        var complement = [UInt32](repeating: 0, count: limbCount)
        var borrow: Int64 = 0
        for i in 0..<limbCount {
            let diff = Int64(modulus[i]) - Int64(b[i]) - borrow
            if diff < 0 {
                complement[i] = UInt32(diff + 0x1_0000_0000)
                borrow = 1
            } else {
                complement[i] = UInt32(diff)
                borrow = 0
            }
        }
        return addMod(a, complement)
    }

    private static func mulMod(_ a: [UInt32], _ b: [UInt32]) -> [UInt32] {
        var product = [UInt64](repeating: 0, count: limbCount * 2)
        for i in 0..<limbCount {
            var carry: UInt64 = 0
            for j in 0..<limbCount {
                let cur = product[i + j] + UInt64(a[i]) * UInt64(b[j]) + carry
                product[i + j] = cur & 0xFFFF_FFFF
                carry = cur >> 32
            }
            product[i + limbCount] += carry
        }
        let low = (0..<limbCount).map { UInt32(product[$0] & 0xFFFF_FFFF) }
        let high = (0..<limbCount).map { UInt32(product[$0 + limbCount] & 0xFFFF_FFFF) }
        return foldReduce(low, high: high)
    }

    /// Modular inverse via Fermat: a^(p-2) mod p. Exponent p-2 = 2^255 - 21, whose
    /// little-endian bytes are `0xEB, 0xFF×30, 0x7F`.
    private static func inverse(_ a: [UInt32]) -> [UInt32] {
        var exponent = [UInt8](repeating: 0xFF, count: 32)
        exponent[0] = 0xEB
        exponent[31] = 0x7F

        var result = fromBytes([1] + [UInt8](repeating: 0, count: 31))
        // Square-and-multiply, most-significant bit first.
        for byteIndex in stride(from: 31, through: 0, by: -1) {
            for bit in stride(from: 7, through: 0, by: -1) {
                result = mulMod(result, result)
                if (exponent[byteIndex] >> UInt8(bit)) & 1 == 1 {
                    result = mulMod(result, a)
                }
            }
        }
        return result
    }

    // MARK: - Reduction helpers

    /// Reduces `low + high·2^256` mod p using 2^256 ≡ 38, then canonicalizes.
    private static func foldReduce(_ low: [UInt32], high: [UInt32]) -> [UInt32] {
        var acc = [UInt64](low.map(UInt64.init))
        // acc += 38 * high, shifted by zero (2^256 folds into the low limbs as ·38).
        var carry: UInt64 = 0
        for i in 0..<limbCount {
            let h = i < high.count ? UInt64(high[i]) : 0
            let cur = acc[i] + 38 * h + carry
            acc[i] = cur & 0xFFFF_FFFF
            carry = cur >> 32
        }
        // Fold the remaining carry (still ·38) until it clears; bounded to a couple
        // of passes because each fold shrinks the overflow toward zero.
        while carry != 0 {
            var next: UInt64 = 38 * carry
            carry = 0
            for i in 0..<limbCount {
                let cur = acc[i] + next
                acc[i] = cur & 0xFFFF_FFFF
                next = cur >> 32
                if next == 0 { break }
            }
            carry = next
        }
        return canonical(acc.map { UInt32($0 & 0xFFFF_FFFF) })
    }

    /// Fully reduces `limbs` (already < 2^256) to the canonical `[0, p)` range by
    /// subtracting p while it fits (at most twice, since input < 2p + 38 < 2^256).
    private static func canonical(_ limbs: [UInt32]) -> [UInt32] {
        var value = limbs
        for _ in 0..<2 {
            guard greaterOrEqualToModulus(value) else { break }
            value = subtractModulus(value)
        }
        return value
    }

    private static func greaterOrEqualToModulus(_ value: [UInt32]) -> Bool {
        for i in stride(from: limbCount - 1, through: 0, by: -1) {
            if value[i] != modulus[i] {
                return value[i] > modulus[i]
            }
        }
        return true // equal counts as ≥
    }

    private static func subtractModulus(_ value: [UInt32]) -> [UInt32] {
        var out = [UInt32](repeating: 0, count: limbCount)
        var borrow: Int64 = 0
        for i in 0..<limbCount {
            let diff = Int64(value[i]) - Int64(modulus[i]) - borrow
            if diff < 0 {
                out[i] = UInt32(diff + 0x1_0000_0000)
                borrow = 1
            } else {
                out[i] = UInt32(diff)
                borrow = 0
            }
        }
        return out
    }

    private static func isZero(_ limbs: [UInt32]) -> Bool {
        canonical(limbs).allSatisfy { $0 == 0 }
    }
}
